Avoid NULL pointer dereference in autoProbeMouse if proto == PROT_UNSUP
Error: Null pointer dereference (CWE 476)
   Read from null pointer 'GetProtocol(proto)'
        at line 3477 of src/mouse.c in function 'autoProbeMouse'.
          Function 'GetProtocol' may return constant 'NULL' at line 736, called at line 3477.
          Null pointer introduced at line 736 in function 'GetProtocol'.

We already handle one of the two cases that make GetProtocol return NULL,
proto == PROTO_UNKNOWN, but not PROT_UNSUP.

[ This bug was found by the Parfait 0.4.2 bug checking tool.
  For more information see http://labs.oracle.com/projects/parfait/ ]

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Reviewed-by: Alexandr Shadchin <alexandr.shadchin@gmail.com>